#!/usr/bin/env python

import os, os.path, sys, getpass, shlex, subprocess

home=os.getenv('HOME')

def getcwd():
    "like os.getcwd(), but collapses the home directory prefix into ~"
    cwd = os.getcwd()
    if cwd.startswith(home):
        cwd = '~'+cwd[len(home):]
    return cwd

def runprogram(argv):
    fdin = sys.stdin
    fdout = sys.stdout
    progname = argv
    if '>' in argv:
	fdout = open(argv[argv.index('>')+1],'w') # open the result file in write mode
	progname = argv[:-2]
    elif '<' in argv:
      	fdin = open(argv[argv.index('<')+1],'r') # open the result file in write mode
      	progname = argv[:-2]
    elif '|' in argv:
	p1 = subprocess.Popen(argv[:argv.index('|')], stdin=fdin, stdout=subprocess.PIPE)
	progname = argv[argv.index('|')+1:]
	fdin=p1.stdout
    subprocess.call(progname , stdin=fdin , stdout=fdout)
    if fdin is not sys.stdin:
	fdin.close()
    elif fdout is not sys.stdout:
	fdout.close()
    return
    
while True:
    print "%s@%s>" % (getpass.getuser(), getcwd()),

    argv = None
    try:
        argv = shlex.split(raw_input())
    except EOFError:
        print
        break                             # end of file from user, e.g. Ctrl-D

    if not argv:
        continue # empty command

    if argv[0] in ['exit', 'quit', 'bye']:
        break
    elif argv[0]=='cd':
        try:
            os.chdir(os.path.expanduser(argv[1])) # expand ~ to home directory
        except IndexError:                   # no arguments, chdir to home dir
            os.chdir(home)
        except OSError, s:
            print >>sys.stderr, "chdir: %s" % s
    else:
	runprogram(argv)

# goodbye message
goodbye = "have a good sunny day, see you back soon"
print "*"+"-"*(len(goodbye)+2)+"*"
print "| %s |" % goodbye
print "*"+"-"*(len(goodbye)+2)+"*"


